#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

mkdir /tmp/patched-physion/ -p
cd /tmp/patched-physion/
p7zip -f -k -d /tmp/physion-wine.7z
cd -
chmod 777 -R /tmp/patched-physion/

while read USUARIO; do
	runuser -l $USUARIO -c "rsync -a /tmp/patched-physion/ /home/$USUARIO/"
	runuser -l $USUARIO -c "mkdir -p .wine/drive_c/users/$USUARIO/Start\ Menu/Programs/Physion/"
	runuser -l $USUARIO -c "cp -f /tmp/Physion.lnk .wine/drive_c/users/$USUARIO/Start\ Menu/Programs/Physion/"
	runuser -l $USUARIO -c "sed 's/USUARIO/$USUARIO/g' /tmp/Physion.desktop > .local/share/applications/wine/Programs/Physion/Physion.desktop"
done < /tmp/homes.list