#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

mkdir /tmp/patched-physion/ -p
cd /tmp/patched-physion/
p7zip -f -k -d /tmp/physion-wine.7z
cd -
chmod 777 -R /tmp/patched-physion/

function geraShort {
	echo "[Desktop Entry]"
	echo "Type=Link"
	cat $1 | \
	grep "Name=" | head -n1
	cat $1 | \
	grep "Name[pt_BR]=" | head -n1
	cat $1 | \
	grep "Icon=" | head -n1
	echo "URL=$2"
}

while read USUARIO; do
	runuser -l $USUARIO -c "rsync -a /tmp/patched-physion/ /home/$USUARIO/"
	runuser -l $USUARIO -c "mkdir -p .wine/drive_c/users/$USUARIO/Start\ Menu/Programs/Physion/"
	runuser -l $USUARIO -c "cp -f /tmp/Physion.lnk .wine/drive_c/users/$USUARIO/Start\ Menu/Programs/Physion/"
	runuser -l $USUARIO -c "sed 's/USUARIO/$USUARIO/g' /tmp/Physion.desktop > .local/share/applications/wine/Programs/Physion/Physion.desktop"
	
	# geraShort /home/$USUARIO/.local/share/applications/wine/Programs/Physion/Physion.desktop \
	# /home/$USUARIO/.local/share/applications/wine/Programs/Physion/Physion.desktop \
	# > /home/$USUARIO/Desktop/Physion.desktop
	cp /home/$USUARIO/.local/share/applications/wine/Programs/Physion/Physion.desktop /home/$USUARIO/Desktop/Physion.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list
